"""phase3: 21 tables (rl_* + mk_*)

Revision ID: d671d5b46602
Revises: 
Create Date: 2026-05-09 18:41:17.326244

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd671d5b46602'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mk_calc_run',
    sa.Column('calc_run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('source_sales_at', sa.DateTime(), nullable=True),
    sa.Column('source_inventory_at', sa.DateTime(), nullable=True),
    sa.Column('source_inbound_at', sa.DateTime(), nullable=True),
    sa.Column('rule_version', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('calc_run_id', name=op.f('pk_mk_calc_run'))
    )
    with op.batch_alter_table('mk_calc_run', schema=None) as batch_op:
        batch_op.create_index('ix_mk_calc_run_status', ['status'], unique=False)
        batch_op.create_index('ix_mk_calc_run_tenant_date', ['tenant_id', 'stat_date'], unique=False)

    op.create_table('mk_export_task',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('scope_json', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_mk_export_task'))
    )
    with op.batch_alter_table('mk_export_task', schema=None) as batch_op:
        batch_op.create_index('ix_mk_export_task_status', ['status'], unique=False)
        batch_op.create_index('ix_mk_export_task_tenant', ['tenant_id'], unique=False)

    op.create_table('mk_forecast_rule',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=True),
    sa.Column('forecast_mode', sa.String(length=20), nullable=False),
    sa.Column('fixed_daily_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_daily_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_3d', sa.Integer(), nullable=False),
    sa.Column('weight_7d', sa.Integer(), nullable=False),
    sa.Column('weight_15d', sa.Integer(), nullable=False),
    sa.Column('weight_30d', sa.Integer(), nullable=False),
    sa.Column('denoise_enabled', sa.Integer(), nullable=False),
    sa.Column('abnormal_dates_json', sa.JSON(), nullable=True),
    sa.Column('abnormal_sales_rule_json', sa.JSON(), nullable=True),
    sa.Column('allow_empty_rule', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("scope_type != 'sku' OR (mall_id IS NOT NULL AND msku IS NOT NULL AND msku != '')", name=op.f('ck_mk_forecast_rule_ck_forecast_rule_sku_scope')),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_mk_forecast_rule'))
    )
    with op.batch_alter_table('mk_forecast_rule', schema=None) as batch_op:
        batch_op.create_index('ix_mk_forecast_rule_scope', ['tenant_id', 'scope_type', 'mall_id', 'msku'], unique=False)

    op.create_table('mk_listing_product_sources',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=50, collation='BINARY'), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=15), nullable=True),
    sa.Column('fnsku', sa.String(length=15), nullable=True),
    sa.Column('delivery_method', sa.String(length=5), nullable=True),
    sa.Column('listing_status', sa.String(length=15), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mk_listing_product_sources'))
    )
    with op.batch_alter_table('mk_listing_product_sources', schema=None) as batch_op:
        batch_op.create_index('ix_mk_lps_delivery_method', ['delivery_method'], unique=False)
        batch_op.create_index('ix_mk_lps_msku_mall', ['tenant_id', 'msku', 'mall_id'], unique=False)
        batch_op.create_index('uq_mk_listing_product_sources_lid', ['tenant_id', 'listing_id'], unique=True)

    op.create_table('mk_purchase_draft',
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('calc_run_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('suggest_qty', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('draft_id', name=op.f('pk_mk_purchase_draft'))
    )
    with op.batch_alter_table('mk_purchase_draft', schema=None) as batch_op:
        batch_op.create_index('ix_mk_purchase_draft_calc_run', ['calc_run_id'], unique=False)
        batch_op.create_index('ix_mk_purchase_draft_status', ['status'], unique=False)

    op.create_table('mk_replenishment_rule',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=True),
    sa.Column('safety_days', sa.Integer(), nullable=False),
    sa.Column('purchase_duration_days', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('qc_days', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=30), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("scope_type != 'sku' OR (mall_id IS NOT NULL AND msku IS NOT NULL AND msku != '')", name=op.f('ck_mk_replenishment_rule_ck_replenishment_rule_sku_scope')),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_mk_replenishment_rule'))
    )
    with op.batch_alter_table('mk_replenishment_rule', schema=None) as batch_op:
        batch_op.create_index('ix_mk_replenishment_rule_scope', ['tenant_id', 'scope_type', 'mall_id', 'msku'], unique=False)

    op.create_table('mk_rule_logistics_method',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('logistics_mode', sa.String(length=30), nullable=False),
    sa.Column('logistics_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mk_rule_logistics_method'))
    )
    with op.batch_alter_table('mk_rule_logistics_method', schema=None) as batch_op:
        batch_op.create_index('ix_mk_rule_logistics_method_rule', ['rule_id'], unique=False)

    op.create_table('mk_sku_forecast_daily',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('calc_run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('forecast_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forecast_source', sa.String(length=30), nullable=True),
    sa.Column('sales_multiplier', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_adjusted', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mk_sku_forecast_daily'))
    )
    with op.batch_alter_table('mk_sku_forecast_daily', schema=None) as batch_op:
        batch_op.create_index('ix_mk_sku_forecast_daily_calc_run', ['calc_run_id'], unique=False)
        batch_op.create_index('uq_mk_sku_forecast_daily_run_tmm_date', ['calc_run_id', 'tenant_id', 'mall_id', 'msku', 'forecast_date'], unique=True)

    op.create_table('mk_sku_inbound_detail',
    sa.Column('inbound_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('inbound_type', sa.String(length=30), nullable=False),
    sa.Column('inbound_status', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('source_order_no', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('inbound_id', name=op.f('pk_mk_sku_inbound_detail'))
    )
    with op.batch_alter_table('mk_sku_inbound_detail', schema=None) as batch_op:
        batch_op.create_index('ix_mk_sku_inbound_detail_arrival', ['expected_arrival_date'], unique=False)
        batch_op.create_index('ix_mk_sku_inbound_detail_tmm', ['tenant_id', 'mall_id', 'msku'], unique=False)

    op.create_table('mk_stockout_event',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('duration_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_mk_stockout_event'))
    )
    with op.batch_alter_table('mk_stockout_event', schema=None) as batch_op:
        batch_op.create_index('ix_mk_stockout_event_start', ['start_at'], unique=False)
        batch_op.create_index('ix_mk_stockout_event_status', ['event_status'], unique=False)
        batch_op.create_index('ix_mk_stockout_event_tmm', ['tenant_id', 'mall_id', 'msku'], unique=False)

    op.create_table('mk_supply_sku_daily_stat',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('calc_run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('msku', sa.String(length=64, collation='BINARY'), nullable=False),
    sa.Column('fnsku', sa.String(length=64), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('asin', sa.String(length=16), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('listing_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('yesterday_sales', sa.Integer(), nullable=True),
    sa.Column('yesterday_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expense_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_profit_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('financial_estimate_type', sa.String(length=20), nullable=True),
    sa.Column('sales_7d', sa.Integer(), nullable=True),
    sa.Column('sales_30d', sa.Integer(), nullable=True),
    sa.Column('sales_60d', sa.Integer(), nullable=True),
    sa.Column('sales_90d', sa.Integer(), nullable=True),
    sa.Column('forecast_daily', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forecast_source', sa.String(length=30), nullable=True),
    sa.Column('coverage_demand', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_7d_raw_daily', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_7d_denoised_daily', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fba_available', sa.Integer(), nullable=True),
    sa.Column('fba_inbound_working', sa.Integer(), nullable=True),
    sa.Column('fba_inbound_shipped', sa.Integer(), nullable=True),
    sa.Column('fba_inbound_receiving', sa.Integer(), nullable=True),
    sa.Column('fba_reserved', sa.Integer(), nullable=True),
    sa.Column('local_actual', sa.Integer(), nullable=True),
    sa.Column('local_plan', sa.Integer(), nullable=True),
    sa.Column('total_stock', sa.Integer(), nullable=True),
    sa.Column('sellable_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fba_sellable_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('local_sellable_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_days', sa.Integer(), nullable=True),
    sa.Column('stockout_date', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('suggest_purchase', sa.Integer(), nullable=False),
    sa.Column('suggest_qty', sa.Integer(), nullable=False),
    sa.Column('suggest_purchase_date', sa.Date(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_as_of', sa.DateTime(), nullable=True),
    sa.Column('suggest_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('suggest_amount_base', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mk_supply_sku_daily_stat'))
    )
    with op.batch_alter_table('mk_supply_sku_daily_stat', schema=None) as batch_op:
        batch_op.create_index('ix_mk_supply_sku_calc_run', ['calc_run_id'], unique=False)
        batch_op.create_index('ix_mk_supply_sku_risk', ['risk_level'], unique=False)
        batch_op.create_index('ix_mk_supply_sku_stockout', ['stockout_date'], unique=False)
        batch_op.create_index('ix_mk_supply_sku_suggest', ['suggest_purchase'], unique=False)
        batch_op.create_index('uq_mk_supply_sku_daily_stat_run_tmm', ['calc_run_id', 'tenant_id', 'mall_id', 'msku'], unique=True)

    op.create_table('mk_tenant_config',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('daily_push_time', sa.Time(), nullable=True),
    sa.Column('source_refresh_times_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_mk_tenant_config'))
    )
    op.create_table('mk_warehouse_mapping',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=100), nullable=True),
    sa.Column('warehouse_type', sa.String(length=30), nullable=False),
    sa.Column('include_in_local_actual', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mk_warehouse_mapping'))
    )
    with op.batch_alter_table('mk_warehouse_mapping', schema=None) as batch_op:
        batch_op.create_index('ix_mk_warehouse_mapping_local', ['include_in_local_actual'], unique=False)
        batch_op.create_index('ix_mk_warehouse_mapping_type', ['warehouse_type'], unique=False)
        batch_op.create_index('uq_mk_warehouse_mapping_tw', ['tenant_id', 'warehouse_id'], unique=True)

    op.create_table('rl_amz_all_listing',
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('amz_listing_id', sa.String(length=15), nullable=True),
    sa.Column('asin', sa.String(length=15), nullable=True),
    sa.Column('parent_asin', sa.String(length=15), nullable=True),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('msku', sa.String(length=50, collation='BINARY'), nullable=False),
    sa.Column('fnsku', sa.String(length=15), nullable=True),
    sa.Column('delivery_method', sa.String(length=5), nullable=True),
    sa.Column('fulfillment_channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fba_estimated_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fbm_available_stock', sa.BigInteger(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('asin_type', sa.String(length=20), nullable=True),
    sa.Column('label_ids', sa.String(length=255), nullable=True),
    sa.Column('default_currency', sa.String(length=20), nullable=False),
    sa.Column('last_pull_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('listing_id', name=op.f('pk_rl_amz_all_listing'))
    )
    with op.batch_alter_table('rl_amz_all_listing', schema=None) as batch_op:
        batch_op.create_index('ix_rl_amz_all_listing_asin', ['tenant_id', 'asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_rl_amz_all_listing_del_flag'), ['del_flag'], unique=False)
        batch_op.create_index('ix_rl_amz_all_listing_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('uq_rl_amz_all_listing_tmm', ['tenant_id', 'msku', 'mall_id'], unique=True)

    op.create_table('rl_amz_finances_profit_mall_100228',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('sp_ads_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sb_ads_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sbv_ads_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sd_ads_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ads_fee_share', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('product_ads_payment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('month_storage_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('permanent_storage_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('excess_storage_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fba_storage_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fba_long_storage_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fba_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fbm_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fba_commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fbm_commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fba_shipment_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rl_amz_finances_profit_mall_100228'))
    )
    with op.batch_alter_table('rl_amz_finances_profit_mall_100228', schema=None) as batch_op:
        batch_op.create_index('uq_rl_finances_profit_tdm', ['tenant_id', 'settlement_date', 'mall_id'], unique=True)

    op.create_table('rl_amz_listing_detail',
    sa.Column('listing_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=50, collation='BINARY'), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('image_url_px75', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=150), nullable=True),
    sa.Column('display_group_title', sa.String(length=250), nullable=True),
    sa.Column('display_group_rank', sa.Integer(), nullable=True),
    sa.Column('classification_title', sa.String(length=250), nullable=True),
    sa.Column('classification_rank', sa.Integer(), nullable=True),
    sa.Column('package_length', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('package_width', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('package_height', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('package_weight', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('start_selling_date', sa.DateTime(), nullable=True),
    sa.Column('first_order_date', sa.DateTime(), nullable=True),
    sa.Column('last_pull_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('listing_detail_id', name=op.f('pk_rl_amz_listing_detail'))
    )
    with op.batch_alter_table('rl_amz_listing_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rl_amz_listing_detail_del_flag'), ['del_flag'], unique=False)
        batch_op.create_index('ix_rl_amz_listing_detail_listing', ['tenant_id', 'listing_id'], unique=False)
        batch_op.create_index('uq_rl_amz_listing_detail_tmm', ['tenant_id', 'mall_id', 'msku'], unique=True)

    op.create_table('rl_amz_manage_fba_inventory',
    sa.Column('manage_inventory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=50, collation='BINARY'), nullable=True),
    sa.Column('fnsku', sa.String(length=15), nullable=True),
    sa.Column('asin', sa.String(length=15), nullable=True),
    sa.Column('afn_fulfillable_quantity', sa.Integer(), nullable=True),
    sa.Column('afn_inbound_working_quantity', sa.Integer(), nullable=True),
    sa.Column('afn_inbound_shipped_quantity', sa.Integer(), nullable=True),
    sa.Column('afn_inbound_receiving_quantity', sa.Integer(), nullable=True),
    sa.Column('reserved_qty', sa.Integer(), nullable=True),
    sa.Column('reserved_customerorders', sa.Integer(), nullable=True),
    sa.Column('reserved_fc_transfers', sa.Integer(), nullable=True),
    sa.Column('reserved_fc_processing', sa.Integer(), nullable=True),
    sa.Column('afn_unsellable_quantity', sa.Integer(), nullable=True),
    sa.Column('afn_total_quantity', sa.Integer(), nullable=True),
    sa.Column('last_pull_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('manage_inventory_id', name=op.f('pk_rl_amz_manage_fba_inventory'))
    )
    with op.batch_alter_table('rl_amz_manage_fba_inventory', schema=None) as batch_op:
        batch_op.create_index('uq_rl_amz_manage_fba_inventory_tmm', ['tenant_id', 'mall_id', 'msku'], unique=True)

    op.create_table('rl_amz_sales_daily_report',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=50, collation='BINARY'), nullable=True),
    sa.Column('year_month_day', sa.String(length=15), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('asin', sa.String(length=50), nullable=True),
    sa.Column('parent_asin', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=5), nullable=True),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_url_px75', sa.String(length=255), nullable=True),
    sa.Column('sales_volume', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rl_amz_sales_daily_report'))
    )
    with op.batch_alter_table('rl_amz_sales_daily_report', schema=None) as batch_op:
        batch_op.create_index('ix_rl_sales_date', ['year_month_day'], unique=False)
        batch_op.create_index('ix_rl_sales_listing', ['listing_id'], unique=False)
        batch_op.create_index('ix_rl_sales_msku_mall', ['msku', 'mall_id'], unique=False)
        batch_op.create_index('uq_rl_sales_tymm', ['tenant_id', 'year_month_day', 'mall_id', 'msku'], unique=True)

    op.create_table('rl_inventory_detail',
    sa.Column('detail_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=350), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('mall_id', sa.BigInteger(), nullable=True),
    sa.Column('msku', sa.String(length=50, collation='BINARY'), nullable=True),
    sa.Column('mall_Identify_code', sa.String(length=30), nullable=True),
    sa.Column('mall_type', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('available_locked_quantity', sa.Integer(), nullable=True),
    sa.Column('defective_quantity', sa.Integer(), nullable=True),
    sa.Column('defective_locked_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('unit_logistics_cost', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('unit_inventory_cost', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('Inventory_value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_inventory_cost', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('owners', sa.String(length=255), nullable=True),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('detail_id', name=op.f('pk_rl_inventory_detail'))
    )
    with op.batch_alter_table('rl_inventory_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rl_inventory_detail_del_flag'), ['del_flag'], unique=False)
        batch_op.create_index('ix_rl_inventory_detail_key', ['key'], unique=False)
        batch_op.create_index('ix_rl_inventory_detail_mall', ['tenant_id', 'mall_id', 'msku'], unique=False)
        batch_op.create_index('ix_rl_inventory_detail_sku', ['sku', 'tenant_id', 'warehouse_id'], unique=False)

    op.create_table('rl_mall',
    sa.Column('mall_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('account', sa.String(length=30), nullable=True),
    sa.Column('mall_name', sa.String(length=50), nullable=True),
    sa.Column('mall_info_id', sa.String(length=32), nullable=True),
    sa.Column('seller_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('mall_status', sa.String(length=10), nullable=True),
    sa.Column('mall_type', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('region', sa.String(length=15), nullable=True),
    sa.Column('marketplace_id', sa.String(length=100), nullable=True),
    sa.Column('aws_region', sa.String(length=20), nullable=True),
    sa.Column('settlement_currency', sa.String(length=10), nullable=True),
    sa.Column('transaction_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('mall_id', name=op.f('pk_rl_mall'))
    )
    with op.batch_alter_table('rl_mall', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rl_mall_del_flag'), ['del_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_rl_mall_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rl_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('prod_line_id', sa.BigInteger(), nullable=True),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('developer_user_id', sa.Integer(), nullable=True),
    sa.Column('responsible_user_ids', sa.String(length=255), nullable=True),
    sa.Column('purchaseer_user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_delivery_date', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('purchasing_notes', sa.String(length=500), nullable=True),
    sa.Column('product_logistics_list', sa.JSON(), nullable=True),
    sa.Column('image_url_px75', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.Column('development_date', sa.Date(), nullable=True),
    sa.Column('shelve_date', sa.Date(), nullable=True),
    sa.Column('first_order_date', sa.Date(), nullable=True),
    sa.Column('label_ids', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('del_flag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_rl_product'))
    )
    with op.batch_alter_table('rl_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rl_product_del_flag'), ['del_flag'], unique=False)
        batch_op.create_index('ix_rl_product_status', ['status'], unique=False)
        batch_op.create_index('uq_rl_product_un', ['del_flag', 'sku', 'tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rl_product', schema=None) as batch_op:
        batch_op.drop_index('uq_rl_product_un')
        batch_op.drop_index('ix_rl_product_status')
        batch_op.drop_index(batch_op.f('ix_rl_product_del_flag'))

    op.drop_table('rl_product')
    with op.batch_alter_table('rl_mall', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rl_mall_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_rl_mall_del_flag'))

    op.drop_table('rl_mall')
    with op.batch_alter_table('rl_inventory_detail', schema=None) as batch_op:
        batch_op.drop_index('ix_rl_inventory_detail_sku')
        batch_op.drop_index('ix_rl_inventory_detail_mall')
        batch_op.drop_index('ix_rl_inventory_detail_key')
        batch_op.drop_index(batch_op.f('ix_rl_inventory_detail_del_flag'))

    op.drop_table('rl_inventory_detail')
    with op.batch_alter_table('rl_amz_sales_daily_report', schema=None) as batch_op:
        batch_op.drop_index('uq_rl_sales_tymm')
        batch_op.drop_index('ix_rl_sales_msku_mall')
        batch_op.drop_index('ix_rl_sales_listing')
        batch_op.drop_index('ix_rl_sales_date')

    op.drop_table('rl_amz_sales_daily_report')
    with op.batch_alter_table('rl_amz_manage_fba_inventory', schema=None) as batch_op:
        batch_op.drop_index('uq_rl_amz_manage_fba_inventory_tmm')

    op.drop_table('rl_amz_manage_fba_inventory')
    with op.batch_alter_table('rl_amz_listing_detail', schema=None) as batch_op:
        batch_op.drop_index('uq_rl_amz_listing_detail_tmm')
        batch_op.drop_index('ix_rl_amz_listing_detail_listing')
        batch_op.drop_index(batch_op.f('ix_rl_amz_listing_detail_del_flag'))

    op.drop_table('rl_amz_listing_detail')
    with op.batch_alter_table('rl_amz_finances_profit_mall_100228', schema=None) as batch_op:
        batch_op.drop_index('uq_rl_finances_profit_tdm')

    op.drop_table('rl_amz_finances_profit_mall_100228')
    with op.batch_alter_table('rl_amz_all_listing', schema=None) as batch_op:
        batch_op.drop_index('uq_rl_amz_all_listing_tmm')
        batch_op.drop_index('ix_rl_amz_all_listing_status')
        batch_op.drop_index(batch_op.f('ix_rl_amz_all_listing_del_flag'))
        batch_op.drop_index('ix_rl_amz_all_listing_asin')

    op.drop_table('rl_amz_all_listing')
    with op.batch_alter_table('mk_warehouse_mapping', schema=None) as batch_op:
        batch_op.drop_index('uq_mk_warehouse_mapping_tw')
        batch_op.drop_index('ix_mk_warehouse_mapping_type')
        batch_op.drop_index('ix_mk_warehouse_mapping_local')

    op.drop_table('mk_warehouse_mapping')
    op.drop_table('mk_tenant_config')
    with op.batch_alter_table('mk_supply_sku_daily_stat', schema=None) as batch_op:
        batch_op.drop_index('uq_mk_supply_sku_daily_stat_run_tmm')
        batch_op.drop_index('ix_mk_supply_sku_suggest')
        batch_op.drop_index('ix_mk_supply_sku_stockout')
        batch_op.drop_index('ix_mk_supply_sku_risk')
        batch_op.drop_index('ix_mk_supply_sku_calc_run')

    op.drop_table('mk_supply_sku_daily_stat')
    with op.batch_alter_table('mk_stockout_event', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_stockout_event_tmm')
        batch_op.drop_index('ix_mk_stockout_event_status')
        batch_op.drop_index('ix_mk_stockout_event_start')

    op.drop_table('mk_stockout_event')
    with op.batch_alter_table('mk_sku_inbound_detail', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_sku_inbound_detail_tmm')
        batch_op.drop_index('ix_mk_sku_inbound_detail_arrival')

    op.drop_table('mk_sku_inbound_detail')
    with op.batch_alter_table('mk_sku_forecast_daily', schema=None) as batch_op:
        batch_op.drop_index('uq_mk_sku_forecast_daily_run_tmm_date')
        batch_op.drop_index('ix_mk_sku_forecast_daily_calc_run')

    op.drop_table('mk_sku_forecast_daily')
    with op.batch_alter_table('mk_rule_logistics_method', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_rule_logistics_method_rule')

    op.drop_table('mk_rule_logistics_method')
    with op.batch_alter_table('mk_replenishment_rule', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_replenishment_rule_scope')

    op.drop_table('mk_replenishment_rule')
    with op.batch_alter_table('mk_purchase_draft', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_purchase_draft_status')
        batch_op.drop_index('ix_mk_purchase_draft_calc_run')

    op.drop_table('mk_purchase_draft')
    with op.batch_alter_table('mk_listing_product_sources', schema=None) as batch_op:
        batch_op.drop_index('uq_mk_listing_product_sources_lid')
        batch_op.drop_index('ix_mk_lps_msku_mall')
        batch_op.drop_index('ix_mk_lps_delivery_method')

    op.drop_table('mk_listing_product_sources')
    with op.batch_alter_table('mk_forecast_rule', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_forecast_rule_scope')

    op.drop_table('mk_forecast_rule')
    with op.batch_alter_table('mk_export_task', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_export_task_tenant')
        batch_op.drop_index('ix_mk_export_task_status')

    op.drop_table('mk_export_task')
    with op.batch_alter_table('mk_calc_run', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_calc_run_tenant_date')
        batch_op.drop_index('ix_mk_calc_run_status')

    op.drop_table('mk_calc_run')
    # ### end Alembic commands ###
